'use strict';
const canvas=document.getElementById('game'),ctx=canvas.getContext('2d'),$=id=>document.getElementById(id);
let W,H,scale,ox,oy,time=0,playing=false,paused=false,armed=false,sound=false,audio,toastTimer=0;
let state, enemies=[],friends=[],particles=[],shots=[],spawn=0,spawnClock=0,cool=0,last=0;
const path=[[-230,330],[150,330],[180,180],[-130,180],[-140,25],[65,25],[65,-150]];
let segs=[],length=0;for(let i=1;i<path.length;i++){let a=path[i-1],b=path[i],l=Math.hypot(b[0]-a[0],b[1]-a[1]);segs.push({a,b,l,start:length});length+=l}
function point(d){d=Math.max(0,Math.min(length,d));const s=segs.find(s=>d<=s.start+s.l)||segs.at(-1),t=(d-s.start)/s.l;return{x:s.a[0]+(s.b[0]-s.a[0])*t,y:s.a[1]+(s.b[1]-s.a[1])*t}}
function reset(persist=true){state={gold:150,hp:100,wave:0,level:1,kills:0};enemies=[];friends=[];particles=[];shots=[];spawn=0;cool=0;recruit('soldier',5,false);if(persist)save()}
function save(){try{localStorage.setItem('bastion-v1',JSON.stringify({...state,friends:friends.map(f=>({type:f.type,hp:f.hp,max:f.max,pos:f.pos})),wave:spawn||enemies.length?Math.max(0,state.wave-1):state.wave}))}catch{}}
function message(s){$('toast').textContent=s;toastTimer=3}
function beep(freq){if(!sound)return;try{audio??=new(window.AudioContext||window.webkitAudioContext)();let o=audio.createOscillator(),g=audio.createGain();o.frequency.value=freq;g.gain.setValueAtTime(.025,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+.08);o.connect(g).connect(audio.destination);o.start();o.stop(audio.currentTime+.09)}catch{}}
function recruit(type,n,pay=true){let cost=type==='archer'?60:40;if(pay&&state.gold<cost)return;if(pay)state.gold-=cost;for(let i=0;i<n;i++){let max=type==='archer'?55:95;friends.push({type,hp:max,max,pos:length-75-Math.random()*105,cd:Math.random(),lane:(Math.random()-.5)*42})}beep(550);if(pay)save()}
function nextWave(){if(spawn||enemies.length||state.wave>=10)return;state.wave++;spawn=24+state.wave*12;spawnClock=0;message('Волна '+state.wave+' — держи строй!');save()}
function burst(x,y,color,n){for(let i=0;i<n;i++)particles.push({x,y,vx:(Math.random()-.5)*100,vy:(Math.random()-.5)*100,life:.5+Math.random()*.5,color})}
function hit(e,d){e.hp-=d;if(e.hp<=0&&!e.dead){e.dead=true;state.gold+=4;state.kills++;burst(e.x,e.y,'#ffcb66',4);beep(240)}}
function resize(){W=innerWidth;H=innerHeight;let d=Math.min(devicePixelRatio||1,2);canvas.width=W*d;canvas.height=H*d;ctx.setTransform(d,0,0,d,0,0);scale=Math.min(W/490,(H-235)/650);ox=W/2;oy=115+(H-235)/2-70*scale}
window.addEventListener('resize',resize);resize();
function proj(x,y,z=0){return[ox+(x-y*.34)*scale,oy+(y*.78-z)*scale]}
function poly(points,color){ctx.fillStyle=color;ctx.beginPath();points.forEach((p,i)=>{let q=proj(...p);i?ctx.lineTo(...q):ctx.moveTo(...q)});ctx.closePath();ctx.fill()}
function line(points,color,width){ctx.strokeStyle=color;ctx.lineWidth=width*scale;ctx.lineCap='round';ctx.lineJoin='round';ctx.beginPath();points.forEach((p,i)=>{let q=proj(...p);i?ctx.lineTo(...q):ctx.moveTo(...q)});ctx.stroke()}
function box(x,y,w,d,h,c){poly([[x,y,0],[x+w,y,0],[x+w,y,h],[x,y,h]],c[1]);poly([[x+w,y,0],[x+w,y+d,0],[x+w,y+d,h],[x+w,y,h]],c[2]);poly([[x,y,h],[x+w,y,h],[x+w,y+d,h],[x,y+d,h]],c[0])}
function tree(x,y){box(x-3,y-3,6,6,20,['#755841','#543f30','#493327']);for(let i=0;i<3;i++){let z=20+i*12,r=24-i*5;poly([[x-r,y,z],[x+r,y,z],[x,y-10,z+34]],['#216647','#26794c','#348752'][i]);poly([[x+r,y,z],[x,y+14,z],[x,y-10,z+34]],'#174f3e')}}
function building(x,y,kind){box(x,y,60,48,kind==='castle'?65:34,['#dbd8bb','#bcb393','#90896e']);let z=kind==='castle'?65:34;poly([[x-6,y-6,z],[x+30,y-6,z+25],[x+66,y-6,z]],'#c28a51');poly([[x+30,y-6,z+25],[x+66,y-6,z],[x+66,y+54,z],[x+30,y+54,z+25]],'#865031');poly([[x-6,y-6,z],[x+30,y-6,z+25],[x+30,y+54,z+25],[x-6,y+54,z]],'#b37546');box(x+22,y-1,18,2,24,['#6b503b','#59432e','#483224']);let p=proj(x+30,y,z+7);ctx.font=`bold ${20*scale}px system-ui`;ctx.textAlign='center';ctx.fillStyle='#ffe296';ctx.fillText(kind==='castle'?'♛':'⚔',...p);if(kind==='castle'){box(x-18,y,20,26,85,['#e2dabc','#b6b097','#8f8975']);box(x+60,y,20,26,85,['#e2dabc','#b6b097','#8f8975']);line([[x+70,y+8,85],[x+70,y+8,120]],'#5d4832',3);poly([[x+70,y+8,120],[x+97,y+8,112],[x+70,y+8,104]],'#4285ed')}}
function unit(u,red){let p=proj(u.x,u.y),sz=(u.boss?1.65:1)*scale;ctx.save();ctx.translate(...p);ctx.scale(sz,sz);ctx.fillStyle='#082c2850';ctx.beginPath();ctx.ellipse(2,2,8,4,0,0,7);ctx.fill();let bob=Math.sin(time*10+u.pos*.1)*1.3;ctx.translate(0,bob);ctx.fillStyle=red?'#ad3037':'#2156b0';ctx.fillRect(-5,-12,10,12);ctx.fillStyle=red?'#f25b54':'#468eea';ctx.fillRect(-6,-21,12,10);ctx.fillStyle=red?'#ff8774':'#84bcff';ctx.fillRect(-5,-22,9,3);ctx.fillStyle='#f5d1a1';ctx.fillRect(-3,-13,6,4);ctx.fillStyle=red?'#8d202c':'#1c467d';ctx.fillRect(-5,-1,4,5);ctx.fillRect(2,-1,4,5);ctx.fillStyle='#d5e3de';ctx.fillRect(7,-17,2,14);ctx.fillStyle=red?'#d14340':'#3d7cd4';ctx.fillRect(-9,-10,5,9);if(u.hp<u.max){ctx.fillStyle='#19372c';ctx.fillRect(-9,-29,18,3);ctx.fillStyle=red?'#f17a70':'#83dfb8';ctx.fillRect(-9,-29,18*Math.max(0,u.hp/u.max),3)}ctx.restore()}
function render(){ctx.fillStyle='#183d35';ctx.fillRect(0,0,W,H);let grd=ctx.createRadialGradient(W*.6,H*.4,10,W/2,H/2,H);grd.addColorStop(0,'#34745c');grd.addColorStop(1,'#102f2d');ctx.fillStyle=grd;ctx.fillRect(0,0,W,H);poly([[-260,-240,-35],[250,-240,-35],[250,420,-35],[-260,420,-35]],'#103d33');poly([[-260,-240,0],[250,-240,0],[250,420,0],[-260,420,0]],'#368563');for(let i=0;i<85;i++){let x=((i*113)%490)-245,y=((i*197)%620)-220;line([[x,y],[x+4,y+1]],'#439471',2)}line(path,'#286549',68);line(path,'#c7b990',56);line(path,'#e3d2a6',43);for(let i=0;i<9;i++){tree(-225+(i%2)*28,-205+i*54);tree(214,-210+i*52)}building(26,-216,'castle');building(-38,-45,'barracks');building(115,-28,'barracks');box(-205,90,40,36,50,['#78998c','#607d72','#466456']);box(-220,130,46,30,28,['#89a398','#607d72','#466456']);let all=[...enemies.filter(e=>!e.dead),...friends];all.sort((a,b)=>a.y-b.y).forEach(u=>unit(u,!!u.enemy));for(let s of shots){line([[s.x,s.y,18],[s.tx,s.ty,18]],'#ffedb6',2)}for(let p of particles){let q=proj(p.x,p.y,10);ctx.globalAlpha=Math.max(0,p.life);ctx.fillStyle=p.color;ctx.beginPath();ctx.arc(...q,4*scale,0,7);ctx.fill()}ctx.globalAlpha=1;if(armed){ctx.fillStyle='#091d2b99';ctx.fillRect(0,0,W,H);ctx.textAlign='center';ctx.fillStyle='#ffdf94';ctx.font='bold 18px system-ui';ctx.fillText('Коснись красной орды',W/2,H*.47)}}
function update(dt){time+=dt;if(toastTimer>0){toastTimer-=dt;if(toastTimer<=0)$('toast').textContent=''}if(!playing||paused)return;cool=Math.max(0,cool-dt);if(spawn>0){spawnClock-=dt;while(spawnClock<=0&&spawn){spawn--;let boss=state.wave%3===0&&spawn===0,max=(22+state.wave*6)*(boss?8:1);enemies.push({enemy:true,boss,hp:max,max,pos:-Math.random()*30,lane:(Math.random()-.5)*40,cd:0});spawnClock+=.18/(1+state.wave*.06)}}
for(let e of enemies){if(e.dead)continue;e.cd-=dt;let target=friends.find(f=>Math.abs(f.pos-e.pos)<24);if(target){if(e.cd<=0){target.hp-=(e.boss?23:9);e.cd=.8;burst(e.x,e.y,'#ffe6a4',2)}}else e.pos+=(e.boss?20:30+state.wave)*dt;if(e.pos>=length){state.hp-=e.boss?15:3;e.dead=true;burst(e.x,e.y,'#ff6b57',8)}let p=point(e.pos);e.x=p.x+e.lane;e.y=p.y}
for(let f of friends){f.cd-=dt;let range=f.type==='archer'?155:29;let target=enemies.find(e=>!e.dead&&Math.abs(e.pos-f.pos)<range);if(target){if(f.cd<=0){hit(target,(f.type==='archer'?15:20)*(1+.25*(state.level-1)));f.cd=f.type==='archer'?.9:.6;shots.push({x:f.x,y:f.y,tx:target.x,ty:target.y,life:.1})}}else{let front=enemies.find(e=>!e.dead);if(front&&f.type==='soldier')f.pos=Math.max(length-420,f.pos-35*dt);else f.pos=Math.min(length-80,f.pos+20*dt)}let p=point(f.pos);f.x=p.x+(f.lane||0);f.y=p.y}friends=friends.filter(f=>f.hp>0);enemies=enemies.filter(e=>!e.dead);for(let p of particles){p.life-=dt;p.x+=p.vx*dt;p.y+=p.vy*dt}particles=particles.filter(p=>p.life>0);shots=shots.filter(s=>(s.life-=dt)>0);
if(state.hp<=0){state.hp=0;finish(false)}else if(state.wave&&spawn===0&&enemies.length===0&&state.active){state.active=false;state.gold+=75+state.wave*10;friends.forEach(f=>f.hp=f.max);save();if(state.wave===10)finish(true);else message('Проход удержан! Награда '+(75+state.wave*10)+' ●')}
state.active=!!(spawn||enemies.length);hud()}
function hud(){$('gold').textContent=state.gold;$('hp').textContent=Math.max(0,Math.ceil(state.hp));$('health').style.width=state.hp+'%';$('waveLabel').textContent='Волна '+Math.max(1,state.wave)+' / 10';$('soldier').disabled=state.gold<40;$('archer').disabled=state.gold<60;$('upgrade').disabled=state.gold<state.level*100;$('upgradeCost').textContent=state.level*100+' ● · уровень '+state.level;$('startWave').disabled=!!(spawn||enemies.length);$('startWave').textContent=spawn||enemies.length?'Идёт бой…':'Волна '+(state.wave+1)+' →';$('status').textContent=spawn||enemies.length?'Защитников: '+friends.length+' · Врагов: '+(enemies.length+spawn):'Найми отряды и начни следующую волну';$('cooldown').textContent=cool>0?'Перезарядка '+Math.ceil(cool)+' с':'Готов · коснись дороги';$('fire').disabled=cool>0}
function finish(win){playing=false;save();$('overlay').classList.remove('hidden');$('overlay').querySelector('h1').innerHTML=win?'Королевство<br>спасено!':'Бастион<br>пал';$('overlay').querySelectorAll('p')[0].textContent='Волна '+state.wave+' · Побеждено врагов: '+state.kills;$('overlay').querySelectorAll('p')[1].textContent=win?'Все 10 волн выдержаны. Начни новый поход!':'Попробуй больше мечников для передовой и лучников для поддержки.';$('play').textContent='Новый поход →';$('resume').classList.add('hidden')}
$('play').onclick=()=>{reset();playing=true;paused=false;$('overlay').classList.add('hidden');hud()};
let saved;try{saved=JSON.parse(localStorage.getItem('bastion-v1'))}catch{}if(saved&&saved.hp>0&&saved.wave<10){$('resume').classList.remove('hidden');$('resume').onclick=()=>{state={...saved};friends=(saved.friends||[]).map(f=>({...f,lane:(Math.random()-.5)*40,cd:0}));playing=true;paused=false;$('overlay').classList.add('hidden');hud()}}reset(false);
$('soldier').onclick=()=>recruit('soldier',5);$('archer').onclick=()=>recruit('archer',3);$('upgrade').onclick=()=>{if(state.gold<state.level*100)return;state.gold-=state.level*100;state.level++;message('Армия усилена!');save()};$('startWave').onclick=nextWave;$('fire').onclick=()=>{if(cool<=0){armed=!armed;message(armed?'Выбери место удара':'Удар отменён')}};$('pause').onclick=()=>{paused=!paused;$('pause').textContent=paused?'▶':'Ⅱ';message(paused?'Пауза':'Бой продолжается')};$('sound').onclick=()=>{sound=!sound;$('sound').style.color=sound?'#efca68':'#fff';beep(700)};
canvas.addEventListener('pointerdown',e=>{if(!armed||paused||!playing)return;armed=false;cool=20;let y=(e.clientY-oy)/(.78*scale),x=(e.clientX-ox)/scale+y*.34;burst(x,y,'#ff974e',60);enemies.forEach(v=>{if(Math.hypot(v.x-x,v.y-y)<95)hit(v,110+state.level*20)});beep(90)});
document.addEventListener('visibilitychange',()=>{if(document.hidden&&playing){paused=true;$('pause').textContent='▶';save()}});window.addEventListener('pagehide',save);
function frame(t){let dt=Math.min((t-last)/1000,.04);last=t;update(dt);render();requestAnimationFrame(frame)}requestAnimationFrame(frame);if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js').catch(()=>{});
