import assert from 'node:assert/strict';
import {Battle,makeLevel,routeLength,pointAt,roadDistance,HOME_SITES,loadProgress,migrateLegacyBattle,defaultHome,updateHome,awardVictory,homeCost,spend} from '../next/core.js';
let pass=0;function test(name,fn){fn();console.log('PASS '+name);pass++}
test('18 valid levels, six biomes and 18 distinct road layouts',()=>{let layouts=new Set(),biomes=new Set();for(let i=1;i<=18;i++){let l=makeLevel(i),len=routeLength(l.path);assert(len>70);let end=pointAt(l.path,len);assert(Math.abs(end.x-l.path.at(-1).x)<1e-8&&Math.abs(end.z+17)<1e-8);biomes.add(l.biome.name);layouts.add(JSON.stringify(l.path));for(let p of l.spots)assert(roadDistance(p,l.path)>2,'plot overlaps road '+i+':'+p.id)}assert.equal(biomes.size,6);assert.equal(layouts.size,18)});
test('building requires gold, correct plot and hero nearby',()=>{let b=new Battle(),p=b.plots[0];assert.equal(b.build(p.id,'archer'),false);b.gold=100;Object.assign(b.hero,{x:p.x,z:p.z});assert.equal(b.build(p.id,'mine'),false);assert.equal(b.build(p.id,'archer'),true);assert.equal(b.gold,0);assert.equal(b.build(p.id,'archer'),false);b.gold=180;assert(b.upgrade(p.id,'heavy'));assert.equal(b.upgrade(p.id,'rapid'),false);assert(b.upgrade(p.id,'heavy'));assert.equal(b.upgrade(p.id,'heavy'),false)});
test('allied and tower kills credit gold immediately; hero drops coins',()=>{let b=new Battle();b.spawnLeft=3;b.spawnEnemy();let e=b.enemies[0];b.damage(e,999,'ally');assert.equal(b.gold,5);b.spawnEnemy();b.damage(b.enemies[1],999,'tower');assert.equal(b.gold,10);b.spawnEnemy();b.damage(b.enemies[2],999,'hero');assert.equal(b.gold,10);assert.equal(b.coins.length,1)});
test('mine income and both branches produce distinct rates',()=>{let values=[];for(let branch of [null,'yield','fast']){let b=new Battle(),p=b.plots[3];Object.assign(p,{type:'mine',level:2,branch,timer:0});b.timer=10000;for(let i=0;i<400;i++)b.update(.05);values.push(b.mineIncome)}assert(values[1]>values[0]);assert(values[2]>values[0])});
test('wave countdown and pause',()=>{let b=new Battle();b.paused=true;b.update(.1);assert.equal(b.timer,7);b.paused=false;for(let i=0;i<71;i++)b.update(.1);assert.equal(b.wave,1);b.spawnLeft=0;b.enemies=[{id:'fake',hp:0}];b.update(.1);assert.equal(b.timer,7);for(let i=0;i<69;i++)b.update(.1);assert.equal(b.wave,1);for(let i=0;i<2;i++)b.update(.1);assert.equal(b.wave,2)});
test('gate absorbs damage before castle, no ordinary building damage',()=>{let b=new Battle();b.spawnLeft=1;b.spawnEnemy();let e=b.enemies[0];e.pos=b.length;e.cd=0;b.hero.x=-14;b.hero.z=22;b.hero.tx=-14;b.hero.tz=22;b.update(.1);assert.equal(b.hp,100);assert(b.gate<60);b.gate=0;e.cd=0;b.update(.1);assert(b.hp<100)});
test('snapshot preserves projectile, enemies, abilities and gold',()=>{let b=new Battle();b.spawnLeft=5;b.spawnEnemy();b.projectile({x:0,z:0},b.enemies[0],10,'archer');b.ability('spin');b.gold=78;let copy=Battle.restore(b.snapshot());assert(copy);assert.deepEqual(copy.snapshot(),b.snapshot());assert.equal(Battle.restore({schema:5,hp:100}),null)});
test('legacy progress and save remain compatible',()=>{let storage={getItem:k=>k==='bastion-meta'?JSON.stringify({campaignUnlocked:8,medals:22,campaignWins:[1,2]}):null};let p=loadProgress(storage);assert.equal(p.meta.campaignUnlocked,8);assert.equal(p.meta.medals,22);let b=migrateLegacyBattle({hp:70,mission:5,gold:98,wave:2,hero:{x:20,y:60},buildings:[{id:'archer',built:true,level:2,spec:'heavy'}]});assert.equal(b.gold,98);assert.equal(b.plots[0].branch,'heavy');assert.equal(b.level.index,5)});
test('kingdom resources distinct from battle and reward only once',()=>{let home=defaultHome(),meta={medals:0,record:0,campaignUnlocked:1,campaignWins:[]};updateHome(home,.1);assert.equal(home.gold,126);let b=new Battle();b.wave=6;let g=home.gold;assert(awardVictory(home,meta,b));assert(home.gold>g);g=home.gold;assert.equal(awardVictory(home,meta,b),false);assert.equal(home.gold,g);assert.equal(b.gold,0);assert.equal(meta.campaignUnlocked,2);assert.equal(spend(home,{gold:999999}),false)});
test('all campaign simulations terminate without invalid values',()=>{let results={victory:0,defeat:0};for(let i=1;i<=18;i++){let b=new Battle(makeLevel(i),{health:2,power:2,armor:1},'normal');b.gold=350;for(let p of b.plots){Object.assign(b.hero,{x:p.x,z:p.z});b.build(p.id,p.category==='economy'?'mine':p.id==='plot0'?'barracks':p.id==='plot1'?'archer':'cannon')}for(let tick=0;tick<25000&&!b.result;tick++){let threat=b.closest(b.hero,80);if(threat){b.hero.tx=threat.x;b.hero.tz=threat.z;if(b.cooldowns.spin<=0)b.ability('spin');if(b.cooldowns.fire<=0)b.ability('fire',threat)}if(b.hp<80&&b.gold>=60)b.repair();b.update(.05);assert(Number.isFinite(b.hp)&&Number.isFinite(b.gold));assert(b.enemies.every(e=>Number.isFinite(e.x)&&Number.isFinite(e.hp)));if(tick%100===0){let copy=Battle.restore(b.snapshot());assert(copy);assert.equal(copy.gold,b.gold)}}assert(b.result,'stalled '+i);results[b.result]++}console.log('Campaign outcomes '+JSON.stringify(results))});
console.log(pass+' tests passed');
