import {View} from './view.js?v=31';
import {Battle,makeLevel,loadProgress,migrateLegacyBattle,HOME_SITES,TYPES,BRANCHES,homeCost,spend,updateHome,awardVictory,clamp,dist,VERSION} from './core.js?v=31';
const $=id=>document.getElementById(id);let storage;try{localStorage.getItem('bastion-meta');storage=localStorage}catch{let m=new Map();storage={getItem:k=>m.get(k),setItem:(k,v)=>m.set(k,v),removeItem:k=>m.delete(k)}}
let {home,meta}=loadProgress(storage),view=new View($('scene')),mode='home',battle=null,userPaused=false,panMode=false,armed=null,trapArmed=null,nearId=null,dismissedPlot=null,toastUntil=0,last=0,saveClock=0,hudClock=0,sound=storage.getItem('bastion-sound')==='1',volume=Number(storage.getItem('bastion-volume')||.45),audio,lastSound=0,dialogFocus=null,low=storage.getItem('bastion-3d-low')==='1';let saved;try{saved=Battle.restore(JSON.parse(storage.getItem('bastion-3d-battle')||'null'),meta)}catch{}let legacy;try{legacy=migrateLegacyBattle(JSON.parse(storage.getItem('bastion-v3')||'null'))}catch{}
view.quality(low);
function notify(s){$('toast').textContent=s;toastUntil=performance.now()+3000}
function sfx(kind){if(!sound||document.hidden||volume<=0)return;try{audio??=new(window.AudioContext||window.webkitAudioContext)();audio.resume();let t=audio.currentTime;if(t-lastSound<.07)return;lastSound=t;let o=audio.createOscillator(),g=audio.createGain();o.type=['fire','shot','heroHit'].includes(kind)?'triangle':'sine';o.frequency.setValueAtTime({gold:800,build:450,wave:160,shot:320,heroHit:600,fire:90,victory:920,castleHit:110}[kind]||350,t);o.frequency.exponentialRampToValueAtTime(80,t+.16);g.gain.setValueAtTime(.03*volume,t);g.gain.exponentialRampToValueAtTime(.001,t+.2);o.connect(g).connect(audio.destination);o.start();o.stop(t+.22)}catch{}}
function save(){try{storage.setItem('bastion-world-v1',JSON.stringify(home));storage.setItem('bastion-meta',JSON.stringify(meta));if(battle&&!battle.result)storage.setItem('bastion-3d-battle',JSON.stringify(battle.snapshot()));}catch{notify('Не удалось сохранить прогресс. Проверь свободное место.')}}
function closeDialog(){let title=$('dialogTitle').textContent;$('dialog').classList.add('hidden');if(battle)battle.paused=userPaused;dialogFocus?.focus?.();dialogFocus=null;if(title==='Что построить?'||title.startsWith('Лучная')||title.startsWith('Пушка')||title.startsWith('Казарма')||title.startsWith('Золотая'))dismissedPlot=nearId;}
function dialog(title,html){dialogFocus=document.activeElement;$('dialogTitle').textContent=title;$('dialogBody').innerHTML=html;$('dialog').classList.remove('hidden');if(battle)battle.paused=true;$('closeDialog').focus()}
function button(label,fn,className='full'){let b=document.createElement('button');b.className=className;b.innerHTML=label;b.onclick=fn;$('dialogBody').appendChild(b);return b}
function card(title,text,cost,fn,disabled=false){let b=document.createElement('button');b.className='card';b.innerHTML='<b>'+title+'</b><span>'+text+'</span><strong>'+cost+'</strong>';b.disabled=disabled;b.onclick=fn;return b}
function cards(){let div=document.createElement('div');div.className='cards';$('dialogBody').appendChild(div);return div}
function costText(c){return c.gold+' ● · '+c.wood+' древесины · '+c.stone+' камня'}
function affordable(c){return Object.keys(c).every(k=>home[k]>=c[k])}
function openHomeSite(site){let s=home.sites[site.id],cost=homeCost(s.level);dialog(site.name,'<p>Уровень '+s.level+'/3 · '+(s.level?'Доход каждые '+(s.branch==='fast'?6:10)+' с':'Участок ещё не освоен')+'. Ресурсы поступают в королевстве.</p>');let c=cards();if(s.level>=3){c.appendChild(card('Полностью развито','Добыча продолжается автоматически.','',()=>{},true));return}if(!s.level)c.appendChild(card('Освоить участок','Построить '+({mine:'шахту',quarry:'карьер',sawmill:'лесопилку'}[site.type])+'.',costText(cost),()=>{if(spend(home,cost)){s.level=1;s.timer=0;save();closeDialog();notify('Участок освоен');sfx('build')}},!affordable(cost)));else for(let b of[{id:'yield',name:'Богатая добыча',text:'Больше ресурсов за один цикл.'},{id:'fast',name:'Быстрая добыча',text:'Ресурсы поступают чаще.'}].filter(b=>!s.branch||b.id===s.branch))c.appendChild(card(b.name,b.text,costText(cost),()=>{if(spend(home,cost)){s.level++;s.branch=b.id;save();closeDialog();notify('Добыча улучшена');sfx('build')}},!affordable(cost)));}
function openCastle(){let cost={gold:150*home.castle,wood:80*home.castle,stone:100*home.castle};dialog('Главный замок','<p>Уровень '+home.castle+'/4. Развитие меняет внешний вид замка. Золото похода остаётся отдельным от ресурсов королевства.</p>');let c=cards();c.appendChild(card('Расширить замок',home.castle<4?'Новые башни, крыши и укрепления.':'Замок полностью развит.',costText(cost),()=>{if(spend(home,cost)){home.castle++;save();closeDialog();notify('Замок расширен');sfx('build')}},home.castle>=4||!affordable(cost)));}
function development(){dialog('Развитие королевства','<p>Несколько участков в открытом мире. Доход идёт, пока ты находишься в королевстве.</p>');let c=cards();c.appendChild(card('Главный замок','Уровень '+home.castle+'/4','',openCastle));for(let site of HOME_SITES)c.appendChild(card(site.name,'Уровень '+home.sites[site.id].level+'/3','',()=>openHomeSite(site)));}
function campaign(){dialog('Походы','<p>Выбери уровень. У каждого похода отдельное золото, другой биом или расположение дорог.</p><div class="campaign" id="levelGrid"></div><label>Сложность<select id="difficulty"><option value="easy">Легко</option><option value="normal" selected>Обычно</option><option value="hard">Сложно</option></select></label><label>Оружие героя<select id="weaponSelect"><option value="sword">Меч</option><option value="spear">Копьё</option><option value="hammer">Молот</option></select></label>');let grid=$('levelGrid');for(let i=1;i<=18;i++){let l=makeLevel(i),b=document.createElement('button');b.innerHTML='<b>'+i+(meta.campaignWins.includes(i)?' ✓':'')+'</b><span>'+l.biome.name+'</span>';b.disabled=i>meta.campaignUnlocked;b.classList.toggle('current',i===meta.campaignUnlocked);b.onclick=()=>startBattle(i,$('difficulty').value,$('weaponSelect').value);grid.appendChild(b)}if(saved)button('Продолжить сохранённый бой',resume);if(!saved&&legacy)button('Перенести сохранение прежней игры',()=>{battle=legacy;legacy=null;saved=battle;resume();notify('Прежний прогресс перенесён. Волна начнётся заново.');save()});}
function homeMode(){save();mode='home';armed=trapArmed=null;userPaused=false;closeDialog();view.setWorld('home',home);$('homeControls').classList.remove('hidden');$('battleControls').classList.add('hidden');$('waveProgress').classList.add('hidden');$('bossBar').classList.add('hidden');$('welcome').classList.add('hidden');nearId=null;dismissedPlot=null;labelsCreate();hud();save()}
function startBattle(i,difficulty='normal',weapon='sword'){if(i>meta.campaignUnlocked)return;save();battle=new Battle(makeLevel(i),meta,difficulty);battle.weaponType=weapon;mode='battle';userPaused=false;closeDialog();view.setWorld('battle',battle);$('homeControls').classList.add('hidden');$('battleControls').classList.remove('hidden');$('waveProgress').classList.remove('hidden');$('welcome').classList.add('hidden');nearId=null;dismissedPlot=null;labelsCreate();notify('Веди героя к врагам. Первая волна через 7 с.');save();hud()}
function resume(){if(!saved)return;battle=saved;saved=null;mode='battle';userPaused=false;closeDialog();view.setWorld('battle',battle);$('homeControls').classList.add('hidden');$('battleControls').classList.remove('hidden');$('waveProgress').classList.remove('hidden');$('welcome').classList.add('hidden');nearId=dismissedPlot=null;labelsCreate();hud();}
function openPlot(p){if(!p)return;nearId=p.id;if(dist(battle.hero,p)>4){battle.hero.tx=p.x;battle.hero.tz=p.z;notify('Герой идёт к площадке');return}dialog(p.type?TYPES[p.type].name+' · уровень '+p.level:'Что построить?','<p>'+(!p.type?'Золото списывается после выбора.':p.level>=3?'Полностью развито.':'Выбери специализацию. Она меняет модель и характеристики.')+'</p>');let c=cards();if(!p.type){for(let type of p.category==='defense'?['barracks','archer','cannon']:['mine']){let d=TYPES[type];c.appendChild(card(d.name,d.description,d.cost+' ●',()=>{if(battle.build(p.id,type)){closeDialog();save();notify(d.name+' построена');sfx('build')}},battle.gold<d.cost))}}else if(p.level<3){let cost=p.level===1?60:120;for(let b of BRANCHES[p.type].filter(b=>!p.branch||p.branch===b.id))c.appendChild(card(b.name,b.text,cost+' ●',()=>{if(battle.upgrade(p.id,b.id)){closeDialog();save();notify('Улучшение готово');sfx('build')}},battle.gold<cost));}else c.appendChild(card('Максимальный уровень',BRANCHES[p.type].find(b=>b.id===p.branch)?.text||TYPES[p.type].description,'',()=>{},true));}
function result(){save();storage.removeItem('bastion-3d-battle');saved=null;let win=battle.result==='victory',first=win&&awardVictory(home,meta,battle);save();dialog(win?'Крепость выстояла':'Замок пал','<div class="result-numbers">Волн: '+battle.wave+' · Врагов побеждено: '+battle.kills+'<br>Доход шахт: '+battle.mineIncome+' ●<br>Золото за бой: '+battle.stats.earned+' ●</div><p>'+(first?'Королевство получило золото, древесину и камень. Открыт следующий поход.':win?'Поход завершён. Награда за первое прохождение уже получена.':'Развивай оборону и попробуй другой вариант башен.')+'</p>');if(win&&battle.level.index<18)button('Следующий поход →',()=>startBattle(battle.level.index+1,battle.difficulty,battle.weaponType),'primary full');if(!win)button('Попробовать снова',()=>startBattle(battle.level.index,battle.difficulty,battle.weaponType),'primary full');if(win)button('Бесконечная оборона',()=>{battle.result=null;battle.endless=true;battle.timer=7;closeDialog();save()});button('В королевство',homeMode,'full');}
function progression(){dialog('Улучшения героя','<p>Медали: '+meta.medals+' ★. Улучшения сохраняются между походами.</p>');let c=cards();let defs={health:['Здоровье','+15 здоровья героя'],magnet:['Сбор монет','Шире радиус сбора'],armor:['Защита замка','−4% входящего урона'],power:['Сила героя','+8% урона'],agility:['Скорость','Герой передвигается быстрее'],focus:['Перезарядка','−4% времени способностей']};for(let[k,[name,desc]]of Object.entries(defs)){let lv=Number(meta[k])||0,cost=3+lv*2;c.appendChild(card(name+' · '+lv+'/5',desc,cost+' ★',()=>{if(meta.medals>=cost&&lv<5){meta.medals-=cost;meta[k]=lv+1;save();progression()}},lv>=5||meta.medals<cost))}}
function settings(){dialog('Меню',mode==='battle'?'<p>Бой на паузе. Сохранение выполняется автоматически.</p>':'<p>Королевство сохраняется на этом устройстве.</p>');if(mode==='battle'){button('Вернуться в бой',closeDialog,'primary full');button('В королевство · сохранить бой',()=>{saved=Battle.restore(battle.snapshot(),meta);homeMode()});button('Ремонт замка +30 ♥ · 60 ●',()=>{if(battle.repair()){save();notify('Замок восстановлен');closeDialog()}else notify('Нужны 60 ● или замок уже цел')});button('Улучшить оружие · 80 ●',()=>{if(battle.gold>=80&&battle.weapon<3){battle.gold-=80;battle.weapon++;save();closeDialog();notify('Оружие усилено')}else notify('Не хватает золота или оружие уже улучшено')});button('Ловушки',()=>{dialog('Ловушки','<p>Выбери ловушку, затем коснись дороги.</p>');for(let[k,n,c]of[['spikes','Шипы',35],['mud','Грязь',30],['barrel','Бочка',45]])button(n+' · '+c+' ●',()=>{trapArmed=k;closeDialog();notify('Коснись дороги, чтобы поставить ловушку')})})}else{button('Продолжить',closeDialog,'primary full');button('Развитие',development);button('Походы',campaign)}button('Постоянные улучшения · '+meta.medals+' ★',progression);let section=document.createElement('div');section.innerHTML='<label>Графика<select id="graphics"><option value="normal">Баланс</option><option value="low">Экономия батареи</option></select></label><label>Яркость радиусов<input id="ranges" type="range" min="15" max="70" value="37"></label><label>Звук<select id="soundSelect"><option value="off">Выключен</option><option value="on">Включён</option></select></label><label>Громкость<input id="volume" type="range" min="0" max="100" value="'+Math.round(volume*100)+'"></label><p class="small">Версия '+VERSION+' · 3D-королевство. Камера не следует за героем.</p><p class="small"><a href="../classic/">Открыть прежнюю игру</a></p>';$('dialogBody').appendChild(section);$('graphics').value=low?'low':'normal';$('graphics').onchange=()=>{low=$('graphics').value==='low';storage.setItem('bastion-3d-low',low?'1':'0');view.quality(low)};$('soundSelect').value=sound?'on':'off';$('soundSelect').onchange=()=>{sound=$('soundSelect').value==='on';storage.setItem('bastion-sound',sound?'1':'0');sfx('build')};$('volume').oninput=()=>{volume=Number($('volume').value)/100;storage.setItem('bastion-volume',volume)};$('ranges').value=storage.getItem('bastion-ranges-3d')||37;$('ranges').oninput=()=>{storage.setItem('bastion-ranges-3d',$('ranges').value);view.setRangeOpacity(Number($('ranges').value)/100)};}
let labelNodes=[];function labelsCreate(){$('labels').replaceChildren();labelNodes=[];let items=mode==='home'?HOME_SITES:battle.plots;for(let p of items){let el=document.createElement('div');el.className='map-label';$('labels').appendChild(el);labelNodes.push({p,el})}}
function labelsUpdate(){let rect=$('scene').getBoundingClientRect();for(let{p,el}of labelNodes){let proj=view.project(p,mode==='home'?0:p.type?0:.1);el.style.left=rect.left+proj.x+'px';el.style.top=rect.top+proj.y+'px';el.hidden=!proj.visible;if(mode==='home'){let s=home.sites[p.id];el.innerHTML=p.name+'<b>'+(s.level?'Ур. '+s.level+' · '+(p.id==='gold'?'●':p.id==='wood'?'древесина':'камень'):'Освоить')+'</b>';}else{let type=p.type?TYPES[p.type]:null;el.classList.toggle('empty',!p.type);el.innerHTML=type?type.name+'<b>'+(p.level===3?'МАКС':'Ур. '+p.level)+'</b>':(p.category==='defense'?'Оборона':'Шахта')+'<b>от '+(p.category==='defense'?60:90)+' ●</b>';if(p.type&&battle.enemies.length>30)el.hidden=true;}}}
function hud(){if(mode==='home'){$('goldLabel').textContent='Ресурсы королевства';$('gold').textContent=Math.floor(home.gold)+' ●';$('secondary').textContent=Math.floor(home.wood)+' древесины · '+Math.floor(home.stone)+' камня';$('location').textContent='Изумрудное королевство';$('health').textContent='Замок · '+home.castle;$('wave').textContent='Поход '+meta.campaignUnlocked+' / 18';$('status').textContent='Касание — вести героя · ✥ — обзор мира';}else{$('goldLabel').textContent='Казна похода';$('gold').textContent=Math.floor(battle.gold)+' ●';$('secondary').textContent='Шахты: +'+battle.mineIncome+' ● за бой';$('location').textContent=battle.level.biome.name;$('health').textContent=Math.ceil(battle.hp)+' ♥ · Герой '+Math.ceil(battle.hero.hp);$('wave').textContent='Волна '+battle.wave+' / '+(battle.endless?'∞':battle.level.waves);$('status').textContent=battle.result?'Бой завершён':armed==='fire'?'Коснись врагов для огненного удара':trapArmed?'Коснись дороги для ловушки':userPaused?'Пауза':battle.enemies.length||battle.spawnLeft?'Врагов '+(battle.enemies.length+battle.spawnLeft)+' · Союзников '+battle.allies.length:'Волна '+(battle.wave+1)+' через '+Math.ceil(Math.max(0,battle.timer))+' с';for(let k of['spin','dash','fire']){$(k).disabled=battle.cooldowns[k]>0||battle.hero.down>0;$(k).querySelector('small').textContent=battle.cooldowns[k]>0?Math.ceil(battle.cooldowns[k])+' с':'Готов'}$('waveProgress').querySelector('i').style.width=((battle.enemies.length||battle.spawnLeft)?100:(1-battle.timer/7)*100)+'%';let boss=battle.enemies.find(e=>e.type==='boss');$('bossBar').classList.toggle('hidden',!boss);if(boss)$('bossHealth').style.width=Math.max(0,boss.hp/boss.max*100)+'%';}$('pause').textContent=userPaused?'▶':'Ⅱ';}
function targetPoint(p){if(!p)return;let hero=mode==='home'?home.hero:battle.hero;let limit=mode==='home'?26:14,zlim=mode==='home'?27:22;if(armed==='fire'&&mode==='battle'){if(battle.ability('fire',p))sfx('fire');armed=null;return}if(trapArmed&&mode==='battle'){if(battle.trap(trapArmed,p)){save();notify('Ловушка установлена')}else notify('Нужны золото и свободное место на дороге');trapArmed=null;return}if(mode==='home'){let site=HOME_SITES.find(s=>dist(p,s)<2.5);if(site&&dist(hero,site)<4){openHomeSite(site);return}if(dist(p,{x:0,z:-9})<4&&dist(hero,{x:0,z:-9})<6){openCastle();return}}else{let plot=battle.plots.find(s=>dist(p,s)<2.5);if(plot){dismissedPlot=null;openPlot(plot);return}}hero.tx=clamp(p.x,-limit,limit);hero.tz=clamp(p.z,-zlim,zlim);dismissedPlot=null;}
let pointers=new Map(),pointerStart=null,lastPinch=0;
$('scene').addEventListener('pointerdown',e=>{if(userPaused||!$('dialog').classList.contains('hidden')||!$('welcome').classList.contains('hidden'))return;$('scene').setPointerCapture(e.pointerId);pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});pointerStart={x:e.clientX,y:e.clientY,move:false};if(pointers.size===2){let p=[...pointers.values()];lastPinch=Math.hypot(p[0].x-p[1].x,p[0].y-p[1].y)}if(!panMode&&pointers.size===1)targetPoint(view.pick(e.clientX,e.clientY));});
$('scene').addEventListener('pointermove',e=>{let old=pointers.get(e.pointerId);if(!old)return;let dx=e.clientX-old.x,dy=e.clientY-old.y;pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});if(pointers.size===2){let p=[...pointers.values()],d=Math.hypot(p[0].x-p[1].x,p[0].y-p[1].y);if(lastPinch>0)view.zoomBy(d/lastPinch);lastPinch=d;}else if(panMode)view.pan(dx,dy);else if(Math.hypot(e.clientX-pointerStart.x,e.clientY-pointerStart.y)>6&&$('dialog').classList.contains('hidden')){let p=view.pick(e.clientX,e.clientY);if(p){let h=mode==='home'?home.hero:battle.hero;h.tx=clamp(p.x,mode==='home'?-26:-14,mode==='home'?26:14);h.tz=clamp(p.z,mode==='home'?-27:-22,mode==='home'?27:22)}}});
function releasePointer(e){pointers.delete(e.pointerId);lastPinch=0}for(let event of['pointerup','pointercancel','lostpointercapture'])$('scene').addEventListener(event,releasePointer);
$('pan').onclick=()=>{panMode=!panMode;$('pan').classList.toggle('active',panMode);notify(panMode?'Обзор: двигай карту пальцем':'Герой: коснись земли')};$('zoomIn').onclick=()=>view.zoomBy(1.15);$('zoomOut').onclick=()=>view.zoomBy(1/1.15);$('center').onclick=()=>view.resetCamera();$('pause').onclick=()=>{userPaused=!userPaused;if(battle)battle.paused=userPaused;hud();save()};$('menuHome').onclick=$('menuBattle').onclick=settings;$('homeDevelop').onclick=development;$('campaign').onclick=campaign;$('closeDialog').onclick=closeDialog;$('enterHome').onclick=homeMode;$('resumeBattle').onclick=resume;$('spin').onclick=()=>{if(battle?.ability('spin'))sfx('heroHit')};$('dash').onclick=()=>{if(battle?.ability('dash'))sfx('heroHit')};$('fire').onclick=()=>{armed=armed==='fire'?null:'fire';notify(armed?'Коснись врагов':'Огонь отменён')};window.addEventListener('resize',()=>view.resize());document.addEventListener('visibilitychange',()=>{save();last=0});window.addEventListener('pagehide',save);window.addEventListener('keydown',e=>{if(e.key==='Escape')closeDialog();if(e.key==='Tab'&&!$('dialog').classList.contains('hidden')){let a=[...$('dialog').querySelectorAll('button:not(:disabled),select,input,a')],first=a[0],end=a.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();end.focus()}else if(!e.shiftKey&&document.activeElement===end){e.preventDefault();first.focus()}}});
$('scene').addEventListener('webglcontextlost',e=>{e.preventDefault();userPaused=true;save();notify('Графика приостановлена. Обнови страницу — прогресс сохранён.');});
function tick(ms){requestAnimationFrame(tick);if(document.hidden){last=0;return}let dt=last?Math.min(.08,(ms-last)/1000):0;last=ms;tick.pending=(tick.pending||0)+dt;if((low||view.renderer.cpu)&&ms-(tick.renderAt||0)<(view.renderer.cpu?66:32))return;dt=Math.min(.1,tick.pending);tick.pending=0;tick.renderAt=ms;if(!$('welcome').classList.contains('hidden'))dt=0;if(mode==='home'&&!userPaused&&$('dialog').classList.contains('hidden')){let h=home.hero,dx=h.tx-h.x,dz=h.tz-h.z,d=Math.hypot(dx,dz);if(d>.1){h.x+=dx/d*Math.min(d,dt*5);h.z+=dz/d*Math.min(d,dt*5);h.angle=Math.atan2(dx,dz)}updateHome(home,dt)}if(mode==='battle'&&battle){let prev=battle.result;battle.update(dt);for(let e of battle.events.splice(0))sfx(e.kind);if(!prev&&battle.result)result();if(!battle.result&&!battle.paused){let near=battle.plots.find(p=>dist(p,battle.hero)<3&&(!p.type||p.level<3));nearId=near?.id||null;if(!near)dismissedPlot=null;if(near&&near.id!==dismissedPlot&&$('dialog').classList.contains('hidden')){dismissedPlot=near.id;openPlot(near)}}}view.render(mode==='home'?home:battle,ms/1000);labelsUpdate();hudClock+=dt;saveClock+=dt;if(hudClock>.15){hud();hudClock=0}if(saveClock>5){save();saveClock=0}if(ms>toastUntil)$('toast').textContent='';}
view.setWorld('home',home);labelsCreate();hud();$('loading').classList.add('hidden');$('welcome').classList.remove('hidden');$('resumeBattle').classList.toggle('hidden',!saved);requestAnimationFrame(tick);
// Read-only diagnostics for support; no player actions or credentials are exposed.
window.bastionDiagnostics=()=>({version:VERSION,mode,webgl:view.renderer.capabilities.isWebGL2,drawCalls:view.renderer.info.render.calls,triangles:view.renderer.info.render.triangles,units:mode==='battle'?battle.enemies.length+battle.allies.length+1:1,level:mode==='battle'?battle.level.index:null,saveSchema:5});

if('serviceWorker' in navigator)navigator.serviceWorker.register('../sw.js?v=31').catch(()=>{});
