export const VERSION=30;
export const clamp=(n,a,b)=>Math.max(a,Math.min(b,n));
export const dist=(a,b)=>Math.hypot(a.x-b.x,a.z-b.z);
export function random(seed){return()=>{seed|=0;seed=seed+0x6D2B79F5|0;let t=Math.imul(seed^seed>>>15,1|seed);t=t+Math.imul(t^t>>>7,61|t)^t;return((t^t>>>14)>>>0)/4294967296}}
export const BIOMES=[{name:'Изумрудная долина',grass:0x6d9450,road:0xd8c29a,water:0x4e9fa8,rock:0x85867c,sky:0xbdd5d0},{name:'Снежный перевал',grass:0xc6d8d7,road:0xadb9b8,water:0x609caf,rock:0x77868e,sky:0xd4e1e9},{name:'Солнечные равнины',grass:0x9bab60,road:0xe4caa0,water:0x50a1a9,rock:0xa2937c,sky:0xe2dcc4},{name:'Туманные земли',grass:0x5d7a66,road:0xacb292,water:0x467e80,rock:0x677573,sky:0xa5bab1},{name:'Песчаная граница',grass:0xc5ab75,road:0xe9cd93,water:0x60aba7,rock:0x9e8a6f,sky:0xe9d8b9},{name:'Сумеречная крепость',grass:0x536d72,road:0xa6b4ab,water:0x4486a0,rock:0x74818e,sky:0x9eb7c9}];
export const TYPES={archer:{name:'Лучная башня',cost:100,range:7.8,damage:20,interval:1.25,description:'Дальняя стрельба. Быстрые или тяжёлые стрелы.'},cannon:{name:'Пушка',cost:150,range:6.7,damage:55,interval:3,description:'Урон по группе. Залп или мощное ядро.'},barracks:{name:'Казарма',cost:60,range:0,damage:0,interval:8,description:'Выпускает отряд. Стража или больше бойцов.'},mine:{name:'Золотая шахта',cost:90,range:0,damage:0,interval:9,description:'Доход в казну. Обильная или быстрая добыча.'}};
export const BRANCHES={archer:[{id:'rapid',name:'Скорострельность',text:'Стреляет на 40% чаще. Урон стрелы −10%.'},{id:'heavy',name:'Тяжёлые стрелы',text:'Урон ×1,8. Лучше против брони.'}],cannon:[{id:'rapid',name:'Залповая батарея',text:'Перезарядка −35%. Два ствола.'},{id:'heavy',name:'Тяжёлая артиллерия',text:'Урон ×1,9. Взрыв шире.'}],barracks:[{id:'guard',name:'Королевская стража',text:'Прочные щиты и +70% здоровья.'},{id:'recruit',name:'Большой гарнизон',text:'На два бойца больше в отряде.'}],mine:[{id:'yield',name:'Богатая жила',text:'Доход за цикл ×1,85.'},{id:'fast',name:'Быстрая добыча',text:'Доход приходит на 40% чаще.'}]};
export function makeLevel(index){index=clamp(Math.floor(index)||1,1,18);const shape=(index-1)%3,flip=Math.floor((index-1)/3)%2?-1:1;const raw=shape===0?[[-11,23],[-11,14],[9,14],[9,3],[-8,3],[-8,-9],[0,-9],[0,-17]]:shape===1?[[10,23],[10,12],[-9,12],[-9,0],[9,0],[9,-11],[0,-11],[0,-17]]:[[-10,23],[-10,16],[3,16],[3,8],[-10,8],[-10,-4],[9,-4],[9,-13],[0,-13],[0,-17]];let castleX=(shape===1?-4:shape===2?4:0)*flip;raw[raw.length-1][0]=castleX/flip;raw[raw.length-2][0]=castleX/flip;let variant=Math.floor((index-1)/6);let path=raw.map(([x,z],i)=>({x:x*flip*(1+variant*.06)||0,z:i===0?23:i===raw.length-1?-17:z+(z>0?-variant*.7:variant*.4)}));let spots=shape===0?[[-6,9],[4,7],[-3,-3],[10,-9],[-6,19]]:shape===1?[[4,17],[-3,6],[3,-5],[-10,-10],[9,6]]:[[-4,20],[-4,12],[-4,1],[3,-10],[9,13]];spots=spots.map(([x,z],i)=>({id:'plot'+i,x:x*flip*(1+variant*.06),z:z+(z>0?-variant*.7:variant*.4),category:i<3?'defense':'economy',type:null,level:0,branch:null,timer:0}));return{index,castle:{...path.at(-1)},biome:BIOMES[(index-1)%6],path,spots,waves:6+Math.floor((index-1)/6)*2,seed:217+index*73};}
export function routeLength(path){return path.slice(1).reduce((n,p,i)=>n+dist(p,path[i]),0)}
export function pointAt(path,d){for(let i=1;i<path.length;i++){let l=dist(path[i],path[i-1]);if(d<=l){let t=clamp(d/l,0,1);return{x:path[i-1].x+(path[i].x-path[i-1].x)*t,z:path[i-1].z+(path[i].z-path[i-1].z)*t,angle:Math.atan2(path[i].x-path[i-1].x,path[i].z-path[i-1].z)}}d-=l}return{...path.at(-1),angle:Math.atan2(path.at(-1).x-path.at(-2).x,path.at(-1).z-path.at(-2).z)}}
export function pointSegmentDistance(p,a,b){let vx=b.x-a.x,vz=b.z-a.z,t=clamp(((p.x-a.x)*vx+(p.z-a.z)*vz)/(vx*vx+vz*vz||1),0,1);return Math.hypot(p.x-a.x-vx*t,p.z-a.z-vz*t)}
export function roadDistance(p,path){return Math.min(...path.slice(1).map((b,i)=>pointSegmentDistance(p,path[i],b)))}
export const HOME_SITES=[{id:'gold',name:'Золотая жила',type:'mine',x:-13,z:9},{id:'stone',name:'Каменный карьер',type:'quarry',x:17,z:4},{id:'wood',name:'Лесной участок',type:'sawmill',x:-16,z:-12}];
export function defaultHome(){return{schema:1,gold:120,wood:80,stone:60,castle:1,sites:{gold:{level:1,branch:null,timer:0},stone:{level:0,branch:null,timer:0},wood:{level:0,branch:null,timer:0}},time:0,rewarded:[],hero:{x:0,z:4,tx:0,tz:4}}}
const safeJSON=s=>{try{return JSON.parse(s)}catch{return null}};
export function loadProgress(storage){let m=safeJSON(storage.getItem('bastion-meta'))||{};let raw=safeJSON(storage.getItem('bastion-world-v1'));let home=defaultHome();if(raw&&raw.schema===1){for(let k of['gold','wood','stone'])home[k]=clamp(Number(raw[k])||0,0,10000000);home.castle=clamp(Number(raw.castle)||1,1,4);home.time=Math.max(0,Number(raw.time)||0);home.rewarded=Array.isArray(raw.rewarded)?raw.rewarded.filter(n=>Number.isInteger(n)&&n>=1&&n<=18):[];for(let k of Object.keys(home.sites)){let s=raw.sites?.[k];if(s)home.sites[k]={level:clamp(Number(s.level)||0,0,3),branch:['yield','fast'].includes(s.branch)?s.branch:null,timer:clamp(Number(s.timer)||0,0,12)}}if(raw.hero&&Number.isFinite(raw.hero.x)&&Number.isFinite(raw.hero.z))home.hero={x:clamp(raw.hero.x,-26,26),z:clamp(raw.hero.z,-27,27),tx:clamp(raw.hero.x,-26,26),tz:clamp(raw.hero.z,-27,27)}}return{home,meta:{...m,medals:Math.max(0,Number(m.medals)||0),record:Math.max(0,Number(m.record)||0),campaignUnlocked:clamp(Number(m.campaignUnlocked)||1,1,18),campaignWins:Array.isArray(m.campaignWins)?m.campaignWins:[]}}}
export function migrateLegacyBattle(data){if(!data?.hero||!Number.isFinite(data.hp)||!Array.isArray(data.buildings))return null;let level=makeLevel(data.mission||1),b=new Battle(level,{},data.difficulty);b.gold=Math.max(0,data.gold||0);b.hp=clamp(data.hp,0,100);b.wave=clamp(data.wave||0,0,level.waves-1);b.timer=5;let convert=p=>({x:clamp((p.x||0)/15,-14,14),z:clamp(((p.y||0)-90)/10,-21,21)});Object.assign(b.hero,convert(data.hero));b.hero.tx=b.hero.x;b.hero.tz=b.hero.z;data.buildings.filter(v=>v.id!=='workshop').forEach((v,i)=>{let s=b.plots[i];if(s&&v.built&&TYPES[v.id])Object.assign(s,{type:v.id,level:clamp(v.level||1,1,3),branch:v.spec||null})});return b;}
export class Battle{
 constructor(level=makeLevel(1),meta={},difficulty='normal'){this.level=level;this.path=level.path;this.length=routeLength(this.path);this.plots=level.spots.map(p=>({...p}));this.meta=meta;this.difficulty=difficulty;this.factor=difficulty==='easy'?.8:difficulty==='hard'?1.25:1;this.gold=0;this.hp=100;this.gate=60;this.wave=0;this.timer=7;this.spawnLeft=0;this.spawnClock=0;this.enemies=[];this.allies=[];this.coins=[];this.shots=[];this.fx=[];this.traps=[];this.events=[];this.time=0;this.kills=0;this.mineIncome=0;this.hero={id:'hero',type:'hero',x:this.path[0].x,z:this.path[0].z-4,tx:this.path[0].x,tz:this.path[0].z-4,hp:100+(meta.health||0)*15,max:100+(meta.health||0)*15,cd:0,angle:Math.PI,attack:0,down:0};this.cooldowns={spin:0,dash:0,fire:0};this.weapon=0;this.weaponType='sword';this.endless=false;this.paused=false;this.result=null;this.nextId=1;this.stats={earned:0,lost:0,heroDown:0,bosses:0};}
 event(kind,data={}){this.events.push({kind,...data});if(this.events.length>100)this.events.shift()}
 goldAdd(n,reason){this.gold+=n;this.stats.earned+=n;if(reason==='mine')this.mineIncome+=n;this.event('gold',{n,reason})}
 build(plotId,type){let p=this.plots.find(p=>p.id===plotId),def=TYPES[type];if(!p||p.type||!def||!((p.category==='defense'&&type!=='mine')||(p.category==='economy'&&type==='mine'))||dist(this.hero,p)>4||this.gold<def.cost)return false;this.gold-=def.cost;Object.assign(p,{type,level:1,timer:0,builtAt:this.time});this.event('build',{plot:p});return true}
 upgrade(plotId,branch){let p=this.plots.find(p=>p.id===plotId),cost=p?.level===1?60:120;if(!p?.type||p.level>=3||dist(this.hero,p)>4||this.gold<cost||!BRANCHES[p.type].some(b=>b.id===branch)||(p.branch&&p.branch!==branch))return false;this.gold-=cost;p.level++;p.branch=branch;p.builtAt=this.time;this.event('build',{plot:p});return true}
 startWave(){if(this.result||this.spawnLeft||this.enemies.length)return false;this.wave++;this.timer=0;this.spawnLeft=Math.min(90,12+this.wave*5+Math.floor(this.level.index/3)*2);this.spawnClock=0;this.event('wave',{wave:this.wave});return true}
 spawnEnemy(){let boss=this.spawnLeft===1&&this.wave%3===0;let roll=(this.spawnLeft+this.wave)%11,type=boss?'boss':roll===0?'siege':roll<3?'runner':roll<5?'armored':roll===5?'ranged':'soldier';let health={boss:350+this.wave*90,siege:140,runner:42,armored:100,ranged:55,soldier:60}[type]*this.factor*(1+.04*this.wave);let e={id:'e'+this.nextId++,type,hp:health,max:health,pos:0,lane:((this.spawnLeft%5)-2)*.6,cd:0,speed:{boss:1,siege:.95,runner:2.45,armored:1.1,ranged:1.2,soldier:1.45}[type],angle:Math.PI,attack:0,slow:0,...this.path[0]};this.enemies.push(e);this.spawnLeft--;}
 damage(e,n,source){if(!e||e.hp<=0)return;n*=e.type==='armored'&&source!=='heavy'?.6:1;e.hp-=n;e.attack=.14;this.fx.push({kind:'hit',x:e.x,z:e.z,life:.22,max:.22,color:source==='heavy'?'orange':'white'});if(e.hp<=0){this.kills++;if(e.type==='boss')this.stats.bosses++;let gold=e.type==='boss'?30:5;if(source==='hero')this.coins.push({x:e.x,z:e.z,n:gold,age:0});else this.goldAdd(gold,'kill');this.event('kill',{type:e.type});}}
 closest(p,range){let target=null,min=range;for(let e of this.enemies){if(e.hp<=0)continue;let d=dist(p,e);if(d<min){target=e;min=d}}return target}
 projectile(source,target,damage,kind,splash=0){this.shots.push({x:source.x,z:source.z,sx:source.x,sz:source.z,targetId:target.id,tx:target.x,tz:target.z,age:0,life:kind==='cannon'?.55:.35,damage,kind,splash});this.event('shot',{kind})}
 ability(kind,target){if(this.result||this.hero.down||this.cooldowns[kind]>0)return false;let h=this.hero;if(kind==='spin'){this.cooldowns.spin=6*(1-(this.meta.focus||0)*.04);this.fx.push({kind:'ring',x:h.x,z:h.z,life:.45,max:.45,r:4,color:'gold'});for(let e of this.enemies)if(dist(h,e)<4)this.damage(e,45+this.weapon*10,'hero');this.event('spin')}
 if(kind==='dash'){this.cooldowns.dash=5*(1-(this.meta.focus||0)*.04);let d=dist(h,{x:h.tx,z:h.tz});let x=d>.1?(h.tx-h.x)/d:Math.sin(h.angle),z=d>.1?(h.tz-h.z)/d:Math.cos(h.angle);h.x=clamp(h.x+x*5,-14,14);h.z=clamp(h.z+z*5,-20,22);h.tx=h.x;h.tz=h.z;this.fx.push({kind:'ring',x:h.x,z:h.z,r:2,life:.3,max:.3,color:'blue'});this.event('dash')}
 if(kind==='fire'){if(!target)return false;this.cooldowns.fire=16*(1-(this.meta.focus||0)*.04);this.fx.push({kind:'blast',...target,r:5,life:.8,max:.8,color:'orange'});for(let e of this.enemies)if(dist(target,e)<5)this.damage(e,100+this.weapon*20,'hero');this.event('fire')}return true}
 trap(kind,p){let costs={spikes:35,mud:30,barrel:45};if(!costs[kind]||this.gold<costs[kind]||roadDistance(p,this.path)>1.7)return false;this.gold-=costs[kind];this.traps.push({...p,kind,life:kind==='mud'?20:60});return true}
 repair(){if(this.gold<60||this.hp>=100)return false;this.gold-=60;this.hp=Math.min(100,this.hp+30);return true}
 update(dt){if(this.paused||this.result)return;dt=Math.min(.1,Math.max(0,dt));this.time+=dt;let wasActive=!!(this.spawnLeft||this.enemies.length);let h=this.hero;for(let k of Object.keys(this.cooldowns))this.cooldowns[k]=Math.max(0,this.cooldowns[k]-dt);h.attack=Math.max(0,h.attack-dt);h.cd-=dt;if(h.down>0){h.down-=dt;if(h.down<=0){h.hp=h.max;h.x=this.level.castle.x;h.z=this.level.castle.z+4;h.tx=h.x;h.tz=h.z}}else{let dx=h.tx-h.x,dz=h.tz-h.z,d=Math.hypot(dx,dz),s=(5+(this.meta.agility||0)*.15)*dt;if(d>.1){h.x+=dx/d*Math.min(s,d);h.z+=dz/d*Math.min(s,d);h.angle=Math.atan2(dx,dz)}let target=this.closest(h,this.weaponType==='spear'?3.2:2.5);if(target&&h.cd<=0){h.angle=Math.atan2(target.x-h.x,target.z-h.z);h.attack=.28;h.cd=this.weaponType==='hammer'?1.05:.55;let dmg=(this.weaponType==='hammer'?40:24)*(1+(this.meta.power||0)*.08)+this.weapon*9;this.damage(target,dmg,'hero');if(this.weaponType==='hammer')for(let e of this.enemies)if(e!==target&&dist(target,e)<2)this.damage(e,dmg*.6,'hero');this.event('heroHit')}}if(dist(h,{x:this.level.castle.x,z:this.level.castle.z+2})<4&&!h.down)h.hp=Math.min(h.max,h.hp+dt*8);
 if(!this.spawnLeft&&!this.enemies.length){this.timer-=dt;if(this.timer<=0){if(this.wave>=this.level.waves&&!this.endless){this.result='victory';this.event('victory');return}this.startWave()}}
 if(this.spawnLeft){this.spawnClock-=dt;while(this.spawnClock<=0&&this.spawnLeft&&this.enemies.length<130){this.spawnEnemy();this.spawnClock+=.32}}
 for(let e of this.enemies){if(e.hp<=0)continue;e.attack=Math.max(0,e.attack-dt);e.cd-=dt;e.slow=Math.max(0,e.slow-dt);let target=!h.down&&dist(e,h)<(e.type==='ranged'?5:1.5)?h:null;if(!target)target=this.allies.find(a=>a.hp>0&&dist(e,a)<1.5);if(target&&e.type!=='runner'){if(e.cd<=0){let dmg=(e.type==='boss'?25:e.type==='siege'?18:9)*this.factor;target.hp-=dmg;e.cd=e.type==='boss'?1.5:1;e.attack=.3;if(target===h&&h.hp<=0){h.hp=0;h.down=4;this.stats.heroDown++;this.event('heroDown')}}}else{e.pos+=e.speed*dt*(e.slow>0?.4:1);let p=pointAt(this.path,e.pos);e.x=p.x+Math.cos(p.angle)*e.lane;e.z=p.z-Math.sin(p.angle)*e.lane;e.angle=p.angle;if(e.pos>=this.length&&e.cd<=0){let dmg=(e.type==='boss'?15:e.type==='siege'?10:4)*this.factor*(1-(this.meta.armor||0)*.04);if(this.gate>0)this.gate=Math.max(0,this.gate-dmg);else this.hp=Math.max(0,this.hp-dmg);e.cd=1.2;e.attack=.3;this.event('castleHit')}}}
 for(let p of this.plots){if(!p.type)continue;p.timer-=dt;let def=TYPES[p.type];if(p.type==='mine'&&p.timer<=0){let n=8+p.level*3+(this.meta.kingdom?.mint||0)*2;if(p.branch==='yield')n=Math.ceil(n*1.85);this.goldAdd(n,'mine');p.timer=def.interval*(p.branch==='fast'?.6:1);p.pulse=.8;this.fx.push({kind:'income',x:p.x,z:p.z,r:1,life:1,max:1,n,color:'gold'})}else if(p.type==='barracks'&&p.timer<=0&&this.allies.length<35){for(let i=0;i<(p.branch==='recruit'?5:3);i++){let hp=p.branch==='guard'?150:90;this.allies.push({id:'a'+this.nextId++,type:p.branch==='guard'?'guard':'ally',x:p.x+(i%3)*.5,z:p.z+1,hp,max:hp,cd:i*.1,attack:0,angle:0})}p.timer=9-Math.min(2,p.level-1)}else if((p.type==='archer'||p.type==='cannon')&&p.timer<=0){let target=this.enemies.filter(e=>e.hp>0&&dist(e,p)<def.range+(p.level-1)*.6).sort((a,b)=>b.pos-a.pos)[0];if(target){let dmg=def.damage*(1+.3*(p.level-1))*(1+(this.meta.kingdom?.arsenal||0)*.05)*(p.branch==='heavy'?(p.type==='cannon'?1.9:1.8):p.branch==='rapid'?.9:1);this.projectile(p,target,dmg,p.type,p.type==='cannon'?(p.branch==='heavy'?3:2):0);p.angle=Math.atan2(target.x-p.x,target.z-p.z);p.pulse=.3;p.timer=def.interval*(p.branch==='rapid'?(p.type==='cannon'?.65:.6):1)}}p.pulse=Math.max(0,(p.pulse||0)-dt)}
 for(let a of this.allies){if(a.hp<=0)continue;a.attack=Math.max(0,a.attack-dt);a.cd-=dt;let e=this.closest(a,30);if(e){let d=dist(a,e);a.angle=Math.atan2(e.x-a.x,e.z-a.z);if(d>1.3){a.x+=(e.x-a.x)/d*2.5*dt;a.z+=(e.z-a.z)/d*2.5*dt}else if(a.cd<=0){a.cd=.8;a.attack=.3;this.damage(e,(a.type==='guard'?19:14)*(1+(this.meta.kingdom?.arsenal||0)*.05),'ally')}}}
 for(let s of this.shots){s.age+=dt;if(s.age>=s.life){let e=this.enemies.find(e=>e.id===s.targetId);let p=e||{x:s.tx,z:s.tz};if(s.splash){for(let v of this.enemies)if(dist(p,v)<s.splash)this.damage(v,s.damage,'heavy');this.fx.push({kind:'blast',...p,r:s.splash,life:.5,max:.5,color:'orange'})}else if(e)this.damage(e,s.damage,'tower')}}this.shots=this.shots.filter(s=>s.age<s.life);
 for(let c of this.coins){c.age+=dt;let d=dist(c,h);if(d<4+(this.meta.magnet||0)*.4&&!h.down){c.x+=(h.x-c.x)*Math.min(1,dt*6);c.z+=(h.z-c.z)*Math.min(1,dt*6);if(d<.8){this.goldAdd(c.n,'coin');c.n=0}}if(c.age>18&&c.n){this.goldAdd(c.n,'coin');c.n=0}}this.coins=this.coins.filter(c=>c.n);
 for(let t of this.traps){t.life-=dt;let victims=this.enemies.filter(e=>e.hp>0&&dist(e,t)<2);if(t.kind==='mud')victims.forEach(e=>e.slow=.5);else if(victims.length){for(let e of victims)this.damage(e,t.kind==='barrel'?110:40,'tower');t.life=0;this.fx.push({kind:'blast',x:t.x,z:t.z,r:2,life:.5,max:.5,color:'orange'})}}this.traps=this.traps.filter(t=>t.life>0);this.fx.forEach(f=>f.life-=dt);this.fx=this.fx.filter(f=>f.life>0).slice(-70);this.enemies=this.enemies.filter(e=>e.hp>0);if(wasActive&&!this.spawnLeft&&!this.enemies.length){this.timer=7;this.event('waveClear')}let dead=this.allies.filter(a=>a.hp<=0);this.stats.lost+=dead.length;this.allies=this.allies.filter(a=>a.hp>0);if(this.hp<=0){this.result='defeat';this.event('defeat')}
 }
 snapshot(){let data={schema:5,levelIndex:this.level.index};for(let k of['gold','hp','gate','wave','timer','spawnLeft','spawnClock','enemies','allies','coins','shots','traps','time','kills','mineIncome','hero','cooldowns','weapon','weaponType','difficulty','stats','plots','endless','nextId'])data[k]=this[k];return JSON.parse(JSON.stringify(data))}
 static restore(data,meta={}){if(data?.schema!==5||!Number.isFinite(data.hp)||!data.hero||![data.hero.x,data.hero.z,data.hero.hp].every(Number.isFinite)||!Array.isArray(data.plots)||!Array.isArray(data.enemies)||data.enemies.length>150)return null;let b=new Battle(makeLevel(data.levelIndex),meta,data.difficulty);for(let k of Object.keys(b.snapshot()))if(k in b&&data[k]!==undefined)b[k]=data[k];b.gold=Math.max(0,Number(b.gold)||0);b.hp=clamp(b.hp,0,100);b.timer=clamp(Number(b.timer)||0,0,7);b.wave=clamp(Number(b.wave)||0,0,999);b.fx=[];return b}
}
export function homeCost(level){return{gold:60+level*50,wood:25+level*20,stone:20+level*20}}
export function spend(home,cost){if(Object.keys(cost).some(k=>home[k]<cost[k]))return false;for(let k of Object.keys(cost))home[k]-=cost[k];return true}
export function updateHome(home,dt){home.time+=dt;for(let site of HOME_SITES){let s=home.sites[site.id];if(!s.level)continue;s.timer-=dt;if(s.timer<=0){s.timer=10*(s.branch==='fast'?.6:1);let n=Math.ceil((4+s.level*2)*(s.branch==='yield'?1.85:1));let key={mine:'gold',quarry:'stone',sawmill:'wood'}[site.type];home[key]+=n}}}
export function awardVictory(home,meta,b){let first=!home.rewarded.includes(b.level.index);if(first){home.rewarded.push(b.level.index);home.gold+=45+b.level.index*8;home.wood+=25;home.stone+=20;meta.medals+=3;meta.campaignUnlocked=Math.min(18,Math.max(meta.campaignUnlocked,b.level.index+1));if(!meta.campaignWins.includes(b.level.index))meta.campaignWins.push(b.level.index)}meta.record=Math.max(meta.record,b.wave);return first}
