import * as T from '../vendor/three.module.js';
// Compatibility renderer. Projects the same 3D meshes when the browser has no WebGL.
// Static geometry is cached; dynamic unit instances are projected independently.
export class SoftwareRenderer{
 constructor(canvas){this.domElement=canvas;this.ctx=canvas.getContext('2d');if(!this.ctx)throw new Error('Canvas is unavailable');this.outputColorSpace=T.SRGBColorSpace;this.shadowMap={enabled:false,type:0};this.capabilities={isWebGL2:false};this.info={render:{calls:0,triangles:0}};this.cache=document.createElement('canvas');this.cacheKey='';this.ratio=1;this.cpu=true;}
 setPixelRatio(r){this.ratio=Math.min(1,r)}
 setSize(w,h){this.domElement.width=Math.round(w*this.ratio);this.domElement.height=Math.round(h*this.ratio);this.cache.width=this.domElement.width;this.cache.height=this.domElement.height;this.cacheKey='';}
 render(scene,camera){scene.updateMatrixWorld(true);camera.updateMatrixWorld(true);let proj=new T.Matrix4().multiplyMatrices(camera.projectionMatrix,camera.matrixWorldInverse),key=camera.position.toArray().join(',')+camera.projectionMatrix.elements.join(',')+scene.children.filter(g=>g.userData.cacheStatic).map(g=>g.uuid+':'+g.children.map(c=>c.uuid).join(',')).join('|'),statics=[];scene.traverse(o=>{if(o.isMesh&&o.visible&&o.userData.staticMesh)statics.push(o)});if(key!==this.cacheKey){this.cacheKey=key;let c=this.cache.getContext('2d');c.fillStyle='#'+scene.background.getHexString();c.fillRect(0,0,this.cache.width,this.cache.height);let tris=[];for(let mesh of statics)this.meshTriangles(mesh,mesh.matrixWorld,proj,tris);this.paint(c,tris);this.staticTriangles=tris.length;}
 this.ctx.drawImage(this.cache,0,0);let tris=[];scene.traverse(o=>{if(!o.isMesh||!o.visible||o.userData.staticMesh)return;let hidden=false;for(let p=o.parent;p;p=p.parent)if(!p.visible)hidden=true;if(hidden)return;if(o.isInstancedMesh){let m=new T.Matrix4(),color=new T.Color();for(let i=0;i<o.count;i++){o.getMatrixAt(i,m);m.premultiply(o.matrixWorld);if(o.instanceColor)o.getColorAt(i,color);this.meshTriangles(o,m,proj,tris,o.instanceColor?color:null)}}else this.meshTriangles(o,o.matrixWorld,proj,tris)});this.paint(this.ctx,tris);this.info.render.triangles=(this.staticTriangles||0)+tris.length;this.info.render.calls=statics.length+tris.length;}
 meshTriangles(mesh,world,proj,tris,instanceColor){let g=mesh.geometry,p=g.attributes.position;if(!p)return;let norm=g.attributes.normal,index=g.index,mat=mesh.material;if(Array.isArray(mat))mat=mat[0];if(mat.opacity===0)return;let m=new T.Matrix4().multiplyMatrices(proj,world),nm=new T.Matrix3().getNormalMatrix(world),points=new Float32Array(p.count*3),v=new T.Vector3(),w=this.domElement.width,h=this.domElement.height;for(let i=0;i<p.count;i++){v.fromBufferAttribute(p,i).applyMatrix4(m);points[i*3]=(v.x+1)*w/2;points[i*3+1]=(1-v.y)*h/2;points[i*3+2]=v.z;}let n=index?index.count:p.count,base=instanceColor||mat.color||new T.Color(0xffffff),normal=new T.Vector3();for(let i=0;i<n;i+=3){let ai=index?index.getX(i):i,bi=index?index.getX(i+1):i+1,ci=index?index.getX(i+2):i+2,a=ai*3,b=bi*3,c=ci*3,x1=points[a],y1=points[a+1],x2=points[b],y2=points[b+1],x3=points[c],y3=points[c+1];if((x2-x1)*(y3-y1)-(y2-y1)*(x3-x1)>=0&&mat.side!==T.DoubleSide)continue;if(Math.max(x1,x2,x3)<0||Math.min(x1,x2,x3)>w||Math.max(y1,y2,y3)<0||Math.min(y1,y2,y3)>h)continue;let shade=1;if(norm&&mat.type!=='MeshBasicMaterial'){normal.fromBufferAttribute(norm,ai).applyMatrix3(nm).normalize();shade=.65+Math.max(0,normal.dot(new T.Vector3(-.4,.8,.45).normalize()))*.4;}let co=base.clone().multiplyScalar(shade);let localY=(p.getY(ai)+p.getY(bi)+p.getY(ci))/3,worldY=world.elements[1]*(p.getX(ai)+p.getX(bi)+p.getX(ci))/3+world.elements[5]*localY+world.elements[9]*(p.getZ(ai)+p.getZ(bi)+p.getZ(ci))/3+world.elements[13];let layer=worldY<.002?0:worldY<.115?1:2;tris.push({layer,y:worldY,p:[x1,y1,x2,y2,x3,y3],depth:(points[a+2]+points[b+2]+points[c+2])/3,color:'#'+co.getHexString(),opacity:mat.opacity??1});}}
 paint(ctx,tris){tris.sort((a,b)=>a.layer-b.layer||(a.layer===1?a.y-b.y:0)||b.depth-a.depth);for(let t of tris){ctx.globalAlpha=t.opacity;ctx.fillStyle=t.color;ctx.beginPath();ctx.moveTo(t.p[0],t.p[1]);ctx.lineTo(t.p[2],t.p[3]);ctx.lineTo(t.p[4],t.p[5]);ctx.closePath();ctx.fill()}ctx.globalAlpha=1;}
}
