import {T,box,cylinder,rock,disc,ring,tree,flag,castle,building,mergeStatic,release,UnitBatch,material} from './models.js?v=30.5';
import {SoftwareRenderer} from './software.js?v=30.5';
import {random,BIOMES,HOME_SITES,roadDistance,TYPES,clamp} from './core.js?v=30.5';
export class View{
 constructor(canvas){this.canvas=canvas;let gl=canvas.getContext('webgl2',{antialias:true});this.renderer=gl?new T.WebGLRenderer({canvas,context:gl,antialias:true,powerPreference:'default'}):new SoftwareRenderer(canvas);this.renderer.outputColorSpace=T.SRGBColorSpace;this.renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));this.renderer.shadowMap.enabled=true;this.renderer.shadowMap.type=T.PCFSoftShadowMap;this.renderer.shadowMap.autoUpdate=false;this.scene=new T.Scene();this.camera=new T.OrthographicCamera(-18,18,28,-28,.1,180);this.focus={x:0,z:0};this.zoom=1;this.mode='home';this.scene.add(new T.HemisphereLight(0xe8f2e3,0x64765b,2.1));let sun=new T.DirectionalLight(0xffedcd,2.3);sun.position.set(-18,40,18);sun.castShadow=true;sun.shadow.mapSize.set(1024,1024);sun.shadow.camera.left=-35;sun.shadow.camera.right=35;sun.shadow.camera.top=35;sun.shadow.camera.bottom=-35;sun.shadow.bias=-.001;this.scene.add(sun);this.sun=sun;this.staticRoot=new T.Group();this.staticRoot.userData.cacheStatic=true;this.scene.add(this.staticRoot);this.buildRoot=new T.Group();this.buildRoot.userData.cacheStatic=true;this.scene.add(this.buildRoot);this.ranges=new T.Group();this.scene.add(this.ranges);this.units=new UnitBatch(this.scene,190);this.effects=new T.Group();this.scene.add(this.effects);this.projectiles=new T.InstancedMesh(new T.SphereGeometry(.14,6,4),new T.MeshBasicMaterial({color:0xe9cf81}),150);this.projectiles.instanceMatrix.setUsage(T.DynamicDrawUsage);this.projectiles.frustumCulled=false;this.scene.add(this.projectiles);this.projectiles.count=0;this.effectPool=[];for(let i=0;i<70;i++){let mesh=new T.Mesh(new T.RingGeometry(.78,1,32),new T.MeshBasicMaterial({color:0xffb34c,transparent:true,opacity:.7,side:T.DoubleSide,depthWrite:false}));mesh.rotation.x=-Math.PI/2;mesh.visible=false;this.effects.add(mesh);this.effectPool.push(mesh)}this.marker=ring(this.scene,0,0,.8,0xf3d681,.9,.1);this.heroRing=ring(this.scene,0,0,.8,0xf5d787,.85,.055);this.ray=new T.Raycaster();this.plane=new T.Plane(new T.Vector3(0,1,0),0);this.dummy=new T.Object3D();this.lastBuildKey='';this.gate=null;this.resize();}
 resize(){let rect=this.canvas.getBoundingClientRect();this.width=rect.width;this.height=rect.height;this.renderer.setSize(rect.width,rect.height,false);this.updateCamera()}
 updateCamera(){let aspect=this.width/this.height,halfH=this.mode==='home'?29:23,halfW=Math.max(this.mode==='home'?15:12.6,halfH*aspect);this.camera.left=-halfW/this.zoom;this.camera.right=halfW/this.zoom;this.camera.top=(halfW/aspect)/this.zoom;this.camera.bottom=-(halfW/aspect)/this.zoom;this.camera.position.set(this.focus.x,55,this.focus.z+37);this.camera.lookAt(this.focus.x,0,this.focus.z);this.camera.updateProjectionMatrix();this.camera.updateMatrixWorld();}
 zoomBy(n){this.zoom=clamp(this.zoom*n,.75,1.8);this.updateCamera()}
 pan(dx,dy){let scale=(this.camera.right-this.camera.left)/this.width;this.focus.x=clamp(this.focus.x-dx*scale,-22,22);this.focus.z=clamp(this.focus.z-dy*scale*1.2,-23,23);this.updateCamera()}
 resetCamera(){this.focus={x:0,z:this.mode==='home'?-2:0};this.zoom=1;this.updateCamera()}
 pick(x,y){let r=this.canvas.getBoundingClientRect();this.ray.setFromCamera(new T.Vector2((x-r.left)/r.width*2-1,-(y-r.top)/r.height*2+1),this.camera);let p=new T.Vector3();if(this.ray.ray.intersectPlane(this.plane,p))return{x:p.x,z:p.z};return null}
 project(p,y=0){let v=new T.Vector3(p.x,y,p.z).project(this.camera);return{x:(v.x+1)/2*this.width,y:(1-v.y)/2*this.height,visible:v.z<1&&Math.abs(v.x)<1&&Math.abs(v.y)<1}}
 clear(root){release(root);while(root.children.length)root.remove(root.children[0]);}
 road(g,path,color,width=2.7){for(let i=1;i<path.length;i++){let a=path[i-1],b=path[i],dx=b.x-a.x,dz=b.z-a.z,l=Math.hypot(dx,dz),angle=Math.atan2(dx,dz);box(g,(a.x+b.x)/2,.025,(a.z+b.z)/2,width+.3,.045,l+.2,0x77836a,'plain',0,angle);box(g,(a.x+b.x)/2,.055,(a.z+b.z)/2,width,.05,l+.2,color,'road',0,angle);disc(g,a.x,a.z,width/2,color,1,.082);disc(g,b.x,b.z,width/2,color,1,.082)}}
 setWorld(mode,data){this.mode=mode;this.data=data;this.clear(this.staticRoot);this.clear(this.buildRoot);this.clear(this.ranges);this.lastBuildKey='';let b=mode==='home'?BIOMES[0]:data.level.biome,rnd=random(mode==='home'?837:data.level.seed),g=new T.Group();this.scene.background=new T.Color(b.sky);this.scene.fog=new T.Fog(b.sky,80,155);let width=mode==='home'?66:35,depth=mode==='home'?74:55;box(g,0,-1.4,0,width,2.8,depth,b.grass,'grass');box(g,0,-2.9,0,width+1,.6,depth+1,0x6c7261);if(mode==='home'){this.road(g,[{x:0,z:26},{x:0,z:7},{x:0,z:-7}],b.road,3);for(let site of HOME_SITES)this.road(g,[{x:0,z:4},{x:site.x*.5,z:site.z},{x:site.x,z:site.z}],b.road,1.6);let water=new T.Group();for(let i=0;i<22;i++){let z=-34+i*3.4,x=25+Math.sin(i*.33)*3;disc(water,x,z,4.6,b.water,1,.012);disc(water,x+.7,z+.5,3.3,0x73b5b7,1,.018)}g.add(water);for(let i=0;i<7;i++)box(g,24,.28,9+i*.4,8,.25,.32,0xb99d6b,'wood');for(let i=0;i<17;i++){let x=-34+i*4.5,z=-32-rnd()*5;cylinder(g,x,2+rnd()*3,z,3+rnd()*3,7+rnd()*5,0x8f9c89,5,0);cylinder(g,x,7,z,1.7,2,0xd6dfd2,5,0)}for(let site of HOME_SITES)for(let i=0;i<6;i++)rock(g,site.x-1.8+rnd()*4,.25,site.z-1.8+rnd()*3,.3+rnd()*.4,site.id==='gold'?0xc7ac62:b.rock);flag(g,0,1,23,0x427ca2);box(g,0,.8,22.5,2,.9,.18,0x7a654b,'wood');}else{this.road(g,data.path,b.road);for(let i=0;i<3;i++){let x=-14+i*14;flag(g,x,1,24,0xa23c35)}for(let x of[-13,13]){box(g,x,.45,22.8,1,.9,1,0x8e7650,'wood');cylinder(g,x+.8,.8,23.2,.65,1.5,0xa25042,4,0)}for(let x of[-22,22])for(let z of[-28,-17,-5,9,22]){let hill=cylinder(g,x,1,z,4+rnd()*2,2+rnd()*2,b.rock,6,.3);hill.rotation.y=rnd()*3}}
 let count=mode==='home'?175:85;for(let i=0;i<count;i++){let x=(rnd()-.5)*width,z=(rnd()-.5)*depth;let occupied=mode==='home'?(Math.abs(x)<4&&z>-12&&z<27)||HOME_SITES.some(s=>Math.hypot(x-s.x,z-s.z)<4)||(x>19):roadDistance({x,z},data.path)<3.5||data.plots.some(p=>Math.hypot(x-p.x,z-p.z)<3.5)||Math.hypot(x,z+17)<6;if(occupied)continue;if(i%5===0)rock(g,x,.2,z,.3+rnd()*.5,b.rock);else tree(g,x,z,.5+rnd()*.5,mode==='battle'&&data.level.index%6===2);}
 for(let i=0;i<110;i++){let x=(rnd()-.5)*width,z=(rnd()-.5)*depth;if(mode==='battle'&&roadDistance({x,z},data.path)<2)continue;for(let j=0;j<2;j++)box(g,x+j*.12,.06,z,.04,.16,.04,mode==='battle'&&data.level.index%6===2?0x9eaf9d:0x92a86a,'plain',0,0,j?.4:-.4)}let terrain=mergeStatic(g);terrain.traverse(o=>{if(o.isMesh)o.userData.staticMesh=true});this.staticRoot.add(terrain);this.resetCamera();this.syncBuildings(data,true)}
 syncBuildings(data,force=false){let key=this.mode==='home'?JSON.stringify([data.castle,Object.values(data.sites).map(s=>[s.level,s.branch])]):JSON.stringify(data.plots.map(p=>[p.type,p.level,p.branch]));if(!force&&key===this.lastBuildKey)return;this.lastBuildKey=key;this.renderer.shadowMap.needsUpdate=true;this.clear(this.buildRoot);this.clear(this.ranges);let g=new T.Group(),c=castle(this.mode==='home'?data.castle:1);c.position.set(this.mode==='home'?0:data.level.castle.x,0,this.mode==='home'?-9:data.level.castle.z);g.add(c);if(this.mode==='home')for(let site of HOME_SITES){let s=data.sites[site.id];if(s.level){let m=building(site.type,s.level,s.branch);m.position.set(site.x,0,site.z);g.add(m)}else ring(this.ranges,site.x,site.z,1.8,0xe5d48c,.8)}else for(let p of data.plots){if(p.type){let m=building(p.type,p.level,p.branch);m.position.set(p.x,0,p.z);g.add(m);if(TYPES[p.type].range)ring(this.ranges,p.x,p.z,TYPES[p.type].range+(p.level-1)*.6,0xe6d7aa,.37,.035)}else{for(let side of[-1,1])for(let i=0;i<6;i++){let pos=-1.6+i*.6;box(g,p.x+pos,.11,p.z+side*1.6,.32,.06,.08,0xe7dca9);box(g,p.x+side*1.6,.11,p.z+pos,.08,.06,.32,0xe7dca9)}}}let compiled=mergeStatic(g);compiled.traverse(o=>{if(o.isMesh)o.userData.staticMesh=true});this.buildRoot.add(compiled);this.gate=this.mode==='battle'?box(this.buildRoot,data.level.castle.x,.9,data.level.castle.z+2.55,1.25,1.8,.09,0x2d383b):null;}
 render(data,time){this.syncBuildings(data);let hero=this.mode==='home'?{...data.hero,type:'hero',angle:data.hero.angle||0,moving:Math.hypot(data.hero.x-data.hero.tx,data.hero.z-data.hero.tz)>.1}:data.hero;let units=this.mode==='home'?[hero]:[...data.enemies,...data.allies,hero].filter(u=>!(u.type==='hero'&&u.down>0));this.units.update(units,time);this.heroRing.position.set(hero.x,.09,hero.z);this.heroRing.visible=!hero.down;if(this.gate)this.gate.visible=data.gate>0;this.marker.position.set(hero.tx,.07,hero.tz);this.marker.visible=!hero.down&&Math.hypot(hero.x-hero.tx,hero.z-hero.tz)>.3;let fx=this.mode==='battle'?data.fx:[];for(let i=0;i<this.effectPool.length;i++){let mesh=this.effectPool[i],f=fx[i];mesh.visible=!!f;if(f){let age=1-f.life/f.max,r=(f.r||.5)*(f.kind==='blast'?.4+age*.6:f.kind==='income'?.4+age:1);mesh.position.set(f.x,.12+age*.2,f.z);mesh.scale.set(r,r,r);mesh.material.opacity=(1-age)*.8;mesh.material.color.setHex({orange:0xf29c3d,white:0xf8eccc,gold:0xf3d076,blue:0x6cb9cf}[f.color]||0xf3d076)}}let shots=this.mode==='battle'?[...data.shots,...data.coins.map(c=>({...c,kind:'coin'}))]:[];let dummy=this.dummy;for(let i=0;i<Math.min(shots.length,150);i++){let s=shots[i];if(s.kind==='coin'){dummy.position.set(s.x,.22+Math.sin(time*4)*.04,s.z);dummy.scale.set(1,.35,1)}else{let t=s.age/s.life;let target=data.enemies.find(e=>e.id===s.targetId);dummy.position.set(s.sx+((target?.x??s.tx)-s.sx)*t,(s.kind==='archer'?3:1)+Math.sin(t*Math.PI)*2-t*2,s.sz+((target?.z??s.tz)-s.sz)*t);dummy.scale.setScalar(s.kind==='cannon'?1.7:.7)}dummy.rotation.set(0,0,0);dummy.updateMatrix();this.projectiles.setMatrixAt(i,dummy.matrix)}this.projectiles.count=Math.min(shots.length,150);this.projectiles.instanceMatrix.needsUpdate=true;this.renderer.render(this.scene,this.camera);}
 quality(low){this.renderer.setPixelRatio(Math.min(devicePixelRatio,low?1:1.5));this.renderer.shadowMap.enabled=!low;this.renderer.shadowMap.needsUpdate=true;this.resize()}
 setRangeOpacity(n){for(let m of this.ranges.children)m.material.opacity=n}
}
